patterns:
  search:
    padding: 2em
    description: This button is to be used with the search bar input.
  back-button:
    padding: 2em
    description: This button should be used inside pages to go back.
  add-to-cart:
    padding: 2em
    description: This button is used with each individual menu item.
  order-again:
    padding: 2em
    description: This button is for users who wish to re-order a previous purchase.
  order-details:
    padding: 2em
    description: This button is used to view the details of a purchased order.
