patterns:
  menu-item-card:
    title: Menu Items
    padding: 2em
    description: This card should be used inside restaurant pages to list individual menu items.
    fields:
      - name: data
        data:
          source: site.data.dishes.popular[0]

  restaurant-card:
    title: Restaurants
    padding: 2em
    description: This card should be used on the home and search page to list each restaurant.
    fields:
      - name: data
        data:
          source: site.restaurants.milanos

  order:
    padding: 2em
    description: This card is used to list open and previous orders on the account page.
