patterns:
  menu-item-card:
    title: Menu Items
    padding: 2em
    description: This card should be used inside restaurant pages to list individual menu items.
  restaurant-card:
    title: Restaurants
    padding: 2em
    description: This card should be used on the home and search page to list each restaurant.
    fields:
      - name: photo
        type: url
        example: "/images/dumpling-house.jpg"
      - name: restaurant
        type: string
        example: "Dumpling House"
      - name: pricerange
        type: string
        example: "$$"
      - name: cuisine
        type: string
        example: "Chinese · Asian Fusion"
      - name: deliverytime
        type: string
        example: "25 min"
      - name: star1
        type: url
        example: "/images/icons.svg#star"
      - name: star2
        type: url
        example: "/images/icons.svg#star"
      - name: star3
        type: url
        example: "/images/icons.svg#star"
      - name: star4
        type: url
        example: "/images/icons.svg#half-star"
  order:
    padding: 2em
    description: This card is used to list open and previous orders on the account page.
